name: Build

on: [push]

jobs:
    HTML5:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: krdlab/setup-haxe@master
              with:
                haxe-version: 4.3.6
            - name: Install Dependencies
              run: |
                haxelib install lime 8.2.3 --quiet
                haxelib install openfl 9.4.1 --quiet
                haxelib install flixel 6.1.0 --quiet --skip-dependencies
                haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons --quiet
                haxelib git haxeui-flixel https://github.com/haxeui/haxeui-flixel --quiet --skip-dependencies
                haxelib git haxeui-core https://github.com/haxeui/haxeui-core --quiet
            - name: Build
              run: |
                haxelib run lime build html5
            - name: Show build files
              run: ls -R bin
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: bin/stable/html5/bin